### PR TITLE
Added onLoad Option which is called after language is loaded.

### PR DESCRIPTION
**Pull request by markdegrootnl**
Added `onLoad` field to the options which is called after language is loaded.

### CODE REVIEW

**Comment by xiCO2k** [comment]
That is awesome!

Can you add just a test method for that addition?

Thanks.

**Comment by markdegrootnl** [comment]
How is this?

**Comment by xiCO2k** [comment]
Awesome, thanks for the PR.

**Comment by xiCO2k** [comment]
Will add to the documentation, and then release probably during the weekend.

**Comment by xiCO2k** [comment]
Tagged on `v2.3.0`.

**Pull request merged**
