### PR TITLE
feat/fix: Allow to opt-out of replacing slashes in keys

### PR DESCRIPTION
**Pull request by BR0kEN-**
https://github.com/xiCO2k/laravel-vue-i18n/issues/115

### CODE REVIEW

**Comment by BR0kEN-** [comment]
@xiCO2k any idea how to fix that without introducing a BC?

**Comment by BR0kEN-** [comment]
Alright, the idea I have come up with to not bring a BC is to introduce the option that allows disabling the errorish (in some cases) behavior.

Covers my use case of the `laravel-vue-i18n` for 100% as I was never intent to use dot/slash notation.

**Comment by xiCO2k** [comment]
Thanks for the PR, will review it and let you know

**Comment by BR0kEN-** [comment]
@xiCO2k please let me know whether this is something that can be expected or should I forget about it.

**Comment by xiCO2k** [comment]
Hey @BR0kEN- I think this is probably not the option.

I think a better way would be to take a look on both json with the full string and with the other way, do you want to make a PR with that?

Thanks again,
Francisco

**Comment by BR0kEN-** [comment]
Didn't get what you meant. What JSON?

**Comment by xiCO2k** [comment]
@BR0kEN- check the PR https://github.com/xiCO2k/laravel-vue-i18n/pull/118 if it looks good to you.

**Pull request closed without merging**
